{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agon-arena.redisHost" . }}
  labels:
    {{- include "agon-arena.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
  selector:
    {{- include "agon-arena.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
