{{- if and (not .Values.api.existingSecretName) .Values.api.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agon-arena.apiSecretName" . }}
  labels:
    {{- include "agon-arena.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.jwtSecretKey }}: {{ .Values.api.jwtSecret | quote }}
  {{- if .Values.api.ed25519PrivateKey }}
  {{ .Values.api.ed25519PrivateKeySecretKey }}: {{ .Values.api.ed25519PrivateKey | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecretName) .Values.postgresql.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agon-arena.postgresqlSecretName" . }}
  labels:
    {{- include "agon-arena.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.passwordSecretKey }}: {{ .Values.postgresql.password | quote }}
{{- end }}
