{{- if and (not .Values.api.existingSecretName) (or .Values.api.jwtSecret .Values.api.ed25519PrivateKey .Values.api.resendApiKey .Values.api.resendFromEmail) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agon-arena.apiSecretName" . }}
  labels:
    {{- include "agon-arena.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.jwtSecretKey }}: {{ .Values.api.jwtSecret | quote }}
  {{- if .Values.api.ed25519PrivateKey }}
  {{ .Values.api.ed25519PrivateKeySecretKey }}: {{ .Values.api.ed25519PrivateKey | quote }}
  {{- end }}
  {{- if and .Values.api.resendApiKeySecretKey .Values.api.resendApiKey }}
  {{ .Values.api.resendApiKeySecretKey }}: {{ .Values.api.resendApiKey | quote }}
  {{- end }}
  {{- if and .Values.api.resendFromEmailSecretKey .Values.api.resendFromEmail }}
  {{ .Values.api.resendFromEmailSecretKey }}: {{ .Values.api.resendFromEmail | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecretName) .Values.postgresql.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agon-arena.postgresqlSecretName" . }}
  labels:
    {{- include "agon-arena.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.passwordSecretKey }}: {{ .Values.postgresql.password | quote }}
{{- end }}
